### ISSUE TITLE
Bardic Inspiration SPLs are missing Spell Name field

### ISSUE THREAD

**Issue by fuzzlecutter** [ArtemiusI/Bardic-Wonders#11]
The `*a.spl` versions of the bardic inspirations (e.g. https://github.com/ArtemiusI/Bardic-Wonders/blob/master/BardicWonders/Inspirations/c0bdi01a.SPL) have empty Spell Name fields, causing them to show up without a name when viewing the effects.

![image](https://github.com/user-attachments/assets/30d9ca5f-d33f-45ab-bec2-2220b651cafc)

The non-a versions do have the Spell Name field. Simply copying over the values to the `*a.spl` versions fixes the issue.

**Comment by ArtemiusI** [comment]
I don't think players would like having to read the inspiration message in their textbox coming from their bard once per round, every round, for the entire game. At least, I definitely wouldn't.
