### ISSUE TITLE
Stormdrummer - Drums of Raijin does not produce lightning

### ISSUE THREAD

**Issue by szaumoor** [ArtemiusI/Bardic-Wonders#4]
Tested with last version. New BG2EE SoA game. Made Jaheira and Minsc hostile. Regular bard song works, and damages them. But upon taking that ability after leveling up with console commands, the bard song, while it adds a pretty electric overlay to my character (really awesome looking btw), it doesn't seem to cause lighting bolts to fall upon my foes. 

Immunity to normal weapons and counter damage also doesn't seem to work. Jaheira was able to damage my character and did not receive any damage.

**Comment by ArtemiusI** [comment]
Fixed. Everything should work as intended now. Although allies may not be affected by the backlash if you force-attack the drummer.
