### ISSUE TITLE
Skald - Battle caster does not work

### ISSUE THREAD

**Issue by szaumoor** [ArtemiusI/Bardic-Wonders#5]
The description states that skalds should be able to cast spells wearing _any_ armor. However, none of the regular armor you find in the room next to where you spawn in BG2EE allow the skald to cast spells.

**Comment by ArtemiusI** [comment]
'Fixed', but with a caveat - I didn't actually change anything, but I removed the Battle Caster description from the skald overhaul itself, because it was only supposed to apply with the Armored Casting component, as was my original design intent.
